name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
         # the create command looks like this:
         # `micromamba create -n test-env python=3.10 numpy`
         environment-name: test-env
         create-args: >-
            python=3.10
            numpy
            Mfront
    - name: cmake
      run: |
         cmake -DCMAKE_BUILD_TYPE=Release . -Denable-c-bindings=ON  -Denable-fortran-bindings=OFF -Denable-python-bindings=ON -Denable-portable-build=ON -Denable-julia-bindings=OFF \
               -DPYTHON_EXECUTABLE:FILEPATH="${CONDA_PREFIX}/bin/python" \
               -DPYTHON_LIBRARY:FILEPATH="$CONDA_PREFIX/lib/libpython310.so" \
               -DPYTHON_LIBRARY_PATH:PATH="$CONDA_PREFIX/lib"
    - name: make
      run: make
    - name: make check
      run: make check
