name: C/C++ CI

on: [push]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      with:
         environment-name: test-env
         create-args: >-
            python=3.9
            numpy
            mfront
    - name: print packages
      run: |
          conda list
    - name: cmake
      run: |
        export TFELHOME=$CONDA_PREFIX
        cmake \
            -DCMAKE_BUILD_TYPE=Release . \
            -Denable-c-bindings=ON  \
            -Denable-fortran-bindings=OFF \
            -Denable-python-bindings=ON \
            -Denable-portable-build=ON \
            -Denable-julia-bindings=OFF \
            -DPYTHON_EXECUTABLE:FILEPATH="${CONDA_PREFIX}/bin/python" \
            -DPYTHON_LIBRARY:FILEPATH="${CONDA_PREFIX}/lib/libpython3.9.so" \
            -DPYTHON_LIBRARY_PATH:PATH="$CONDA_PREFIX/lib"
    - name: make
      run: make VERBOSE=1
    - name: make check
      run: make check
