name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release . -Denable-c-bindings=ON  -Denable-fortran-bindings=OFF -Denable-python-bindings=ON -Denable-portable-build=ON -Denable-julia-bindings=OFF
    - name: make
      run: make
    - name: make check
      run: make check
