name: Python bindings CI

on: [push]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=3.9
            numpy
            mfront
            cmake

      - name: print packages
        run: |
          conda list

      - name: cmake
        run: |
          echo "CMAKE_HAVE_LIBC_PTHREAD=${CMAKE_HAVE_LIBC_PTHREAD}"
          cmake --version
          which cmake
          
          export TFELHOME=$CONDA_PREFIX
          cmake \
              -DCMAKE_BUILD_TYPE=Release . \
              -Denable-c-bindings=ON  \
              -Denable-fortran-bindings=OFF \
              -Denable-python-bindings=ON \
              -Denable-portable-build=ON \
              -Denable-julia-bindings=OFF \
              -DPYTHONLIBS_VERSION_STRING="39" \
              -DPython_ADDITIONAL_VERSIONS="3.9" \
              -DPYTHON_EXECUTABLE:FILEPATH="${CONDA_PREFIX}/bin/python" \
              -DPYTHON_LIBRARY:FILEPATH="${CONDA_PREFIX}/lib/libpython3.9.so" \
              -DPYTHON_LIBRARY_PATH:PATH="$CONDA_PREFIX/lib"
      - name: make
        run: make VERBOSE=1
      - name: make check
        run: make check

  boa_build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            boa

      - name: boa build
        run: |
          boa build . --python=3.9
        working-directory: conda